version: "3.8"

services:
  mysql-tsc-service:
    image: mysql:8.0
    container_name: tsc_mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3308:3306"
    volumes:
      - ./.mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "tsc"
      MYSQL_USER: "tsc"
      MYSQL_PASSWORD: "tsc"
      MYSQL_ROOT_PASSWORD: "tsc"
